#!/bin/bash

# Afficher le menu et capturer la sélection
selection=$(echo -e "󰔛 05 min\n󰔛 10 min\n󰔛 15 min\n󰔛 20 min\n󰔛 25 min\n󰔛 30 min"| rofi -dmenu -config ~/.config/rofi/alarm-window.rasi)

# Vérifier si une sélection a été faite
if [[ -n "$selection" ]]; then
    case "$selection" in
        "󰔛 05 min")
			foot termdown -bt Terminé -f standard 5m
			;;
        "󰔛 10 min")
			foot termdown -bt Terminé -f standard 10m
            ;;
        "󰔛 15 min")
        	foot termdown -bt Terminé -f standard 15m
            ;;  
        "󰔛 20 min")
			foot termdown -bt Terminé -f standard 20m
            ;;      
              
        "󰔛 25 min")
			foot termdown -bt Terminé -f standard 25m
            ;;
         
        "󰔛 30 min")
			foot termdown -bt Terminé -f standard 30m
            ;;
    esac
fi   
